# Файл docker-compose.yml для Django-приложения с базой данных PostgreSQL
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://dedida:qwe123asd321@db:5432/dedida
      - DJANGO_SETTINGS_MODULE=config.settings
  db:
    image: postgres:17
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dedida", "-h", "localhost", "-p", "5432"]
      interval: 30s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=dedida
      - POSTGRES_PASSWORD=qwe123asd321
      - POSTGRES_DB=dedida
    ports:
      - "5432:5432"