# Generated by Django 5.1.3 on 2024-11-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='folder',
        ),
    ]
